services:
  - type: web
    name: kouverte-vox
    runtime: node
    plan: free
    autoDeploy: true
    branch: main
    buildCommand: npm install
    startCommand: node vox-server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: WEBAPP_URL
        value: https://www.kouverte.com/app.html
      - key: BITCOIN_ADDRESS
        value: bc1qssg5wplzn8a0euf8sp03uthwyuep48k7zw9c00
      - key: BITCOIN_MIN_CONFIRMATIONS
        value: "4"
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: Kouverte_bot
